title: Basil Thalakkodan
logo: BASIL 24.jpg
show_downloads: true
theme: jekyll-theme-minimal
color_scheme: dark


description: >-
  Data Analyst | Power BI | Tableau | SQL | Excel |
  Helping businesses make informed decisions by developing clear and compeliing dashboards

